# Generated by Django 4.2.6 on 2023-10-11 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cat-img/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('words_list', models.TextField()),
                ('game_id', models.CharField(default=uuid.UUID('19e61cee-59b6-41dc-a634-5003dda94a71'), max_length=240)),
                ('key', models.CharField(default=uuid.UUID('73564956-8381-4808-b431-ebcf594bf49c'), max_length=240)),
                ('isDisable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
