# Generated by Django 4.2.6 on 2023-10-17 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default=uuid.UUID('aad5bdba-b439-4a15-a2d7-881b650b74da'), max_length=240),
        ),
        migrations.AlterField(
            model_name='game',
            name='key',
            field=models.CharField(default=uuid.UUID('c28b0d22-6126-4130-9af5-2f0aa2adae1a'), max_length=240),
        ),
    ]
